
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql:///sell?useUnicode=true&useSSL=false&autoReconnect=true
  jpa:
    show-sql: true
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8085
